/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.*;
import ModeloDAO.AutomovilDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;//exportando el paquete que contine la clase DefaultTable Model

/**
 *
 * @author andyl
 */
public class ConsultaAutomovil extends javax.swing.JFrame { //DEFINE LA CLASE consultaAutomovil QUE EXTIENDE AL JFRAME haciendo que sea una ventana de aplicacion swim

    
    public ConsultaAutomovil() { //Constructor de la clase consultaAutomovil
        initComponents(); //LLAMA AL METODO "initcomponentes"  que inicializa los componentes de la interfaz grafica  (autogenerado por netbeans)
        cargarTabla(); //LLAMA A "CARGARTABLA" PARA CARGAR LOS DATOS EN LA TABLA DE INICIAR LA APLICACION
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAutomoviles = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(212, 238, 238));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setText("Consulta de automóviles");

        tblAutomoviles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Modelo", "Marca", "Motor", "Color", "Patente", "Cantidad Puertas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAutomoviles);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(355, 355, 355)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cargarTabla() { //Metodo para cargar los datos de los automoviles en la tabla
        try { //excepciones
            // Es el array que hace referencia al encabezado de la tabla para cuando se muestre este frame lo haga con esos encabezados
            jScrollPane2.setViewportView(tblAutomoviles);//cuando el contenido excede el area visible, se pueden utilizar barras de desplazamiento
            //Añade la tabla tblAutomoviles al jScrollPane2.
            String campos[] = new String[]{"ID", "Modelo", "Marca", "Motor", "Color", "Patente", "Cantidad Puerta"};// ARREGLO DE CADENAS CON LOS NOMBRES DE LAS COLUMNAS DE LA TABLA
            DefaultTableModel dtm = new DefaultTableModel(null, campos); //Crea un modelo de tabla vacío (null para los datos iniciales) pero con las columnas definidas en el arreglo campos.
            tblAutomoviles.setModel(dtm); //ASIGNA EL MODELO DE LA TABLA DTM A tblAutomoviles
            
            List<Automovil> automoviles = new AutomovilDAO().listarAutomovil();//Creamos un arreglo (lista) con el objeto automovil
            // Obtiene una lista de automóviles llamando al método listarAutomovil del AutomovilDAO.
            DefaultTableModel dt = (DefaultTableModel) tblAutomoviles.getModel();//obtiene el metodo de la tabla actual
            // size() tamñano de la lista
          
            for (int i = 0; i < automoviles.size(); i++) { //(FOR EVALUACION 2)  //se inicia un bucle for que itera sobre la lista adao que contiene los objetos "automovil"
                String datos[] = new String[]{ //arreglo de cadenas para alamcenar los valores de los atributos de cada automovil de la lista 
                    automoviles.get(i).getId() + "",
                    automoviles.get(i).getModelo(),
                    automoviles.get(i).getMarca(),
                    automoviles.get(i).getMotor(), //Para cada automóvil, crea un arreglo de cadenas datos con los atributos del automóvil convertidos a String.
                    automoviles.get(i).getColor(),
                    automoviles.get(i).getPatente(),
                    automoviles.get(i).getCantPuertas() + ""
                };
                dt.addRow(datos);//row = fila de la tabla, y addrow seria agregar fila 
            }
            //El ciclo for recorre cada automóvil en la lista automoviles, crea un arreglo de cadenas datos 
            //con los atributos del automóvil actual, y luego agrega ese arreglo como una nueva fila en el modelo de la tabla DefaultTableModel.
            //Esto permite que la tabla tblAutomoviles muestre la información de todos los automóviles en la lista.

        } catch (Exception ex) { //captura cualquier excepcion
            System.out.println("Error: " + ex.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAutomoviles;
    // End of variables declaration//GEN-END:variables
}
